title: Throwaway
description: Experimenting with the Just the Docs theme
theme: just-the-docs

url: https://sqlsauce.github.io/throwaway

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
